# ARTUR KOMPAŁA

a. Utwórz jednowymiarową tablicę Numpy zawierającą liczby od 1 do 20.

b. Wyznacz sumę, średnią, medianę oraz wariancję elementów tablicy.

c. Przekształć jednowymiarową tablicę w dwuwymiarową o wymiarach 5x4.

In [160]:
import numpy as np
#a
arr = np.arange(1,21)
print("a. Tablica od 1 do 20:\n", arr)
#b
print("b. Suma:", np.sum(arr))
print("Średnia:", np.mean(arr))
print("Mediana:", np.median(arr))
print("Wariancja:", np.var(arr))
#c
arr_2d = arr.reshape(5,4)
print("c. Tablica 5x4:\n", arr_2d)

a. Tablica od 1 do 20:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
b. Suma: 210
Średnia: 10.5
Mediana: 10.5
Wariancja: 33.25
c. Tablica 5x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


a. Utwórz dwie macierze 3x3 z losowych liczb całkowitych z zakresu od 0 do 10.

b. Wykonaj operacje dodawania, odejmowania, mnożenia macierzy oraz iloczyn
macierzy (mnożenie macierzowe).

c. Oblicz wyznacznik oraz macierz odwrotną (tylko da jednej).

In [161]:
#a
arr1 = np.random.randint(0, 10, (3, 3))
arr2 = np.random.randint(0, 10, (3, 3))
print("a. Macierz 1:\n", arr1)
print("Macierz 2:\n", arr2)
#b
print("b. Dodawanie:\n", arr1 + arr2)
print("Odejmowanie:\n", arr1 - arr2)
print("Mnożenie elementów:\n", arr1 * arr2)
print("Iloczyn macierzy:\n", np.dot(arr1, arr2))
#c
det = np.linalg.det(arr1)
inv = np.linalg.inv(arr1)
print("c. Wyznacznik macierzy 1:", det)
print("Macierz odwrotna macierzy 1:\n", inv)


a. Macierz 1:
 [[0 7 6]
 [8 6 0]
 [9 5 3]]
Macierz 2:
 [[9 2 6]
 [9 5 5]
 [6 3 7]]
b. Dodawanie:
 [[ 9  9 12]
 [17 11  5]
 [15  8 10]]
Odejmowanie:
 [[-9  5  0]
 [-1  1 -5]
 [ 3  2 -4]]
Mnożenie elementów:
 [[ 0 14 36]
 [72 30  0]
 [54 15 21]]
Iloczyn macierzy:
 [[ 99  53  77]
 [126  46  78]
 [144  52 100]]
c. Wyznacznik macierzy 1: -252.00000000000003
Macierz odwrotna macierzy 1:
 [[-0.07142857 -0.03571429  0.14285714]
 [ 0.0952381   0.21428571 -0.19047619]
 [ 0.05555556 -0.25        0.22222222]]


a. Utwórz macierz 6x6 z liczbami całkowitymi od 1 do 36.

b. Wydziel podmacierz 3x3 z lewego górnego rogu macierzy.

c. Zmień elementy na przekątnej macierzy na wartość 0.

d. Wyświetl wszystkie elementy macierzy większe niż 20.

In [162]:
#a
arr = np.arange(1, 37).reshape(6, 6)
print("a. 6x6:\n", arr)
#b
submatrix = arr[:3, :3]
print("b. Podmacierz 3x3 z lewego górnego rogu:\n", submatrix)
#c
np.fill_diagonal(arr, 0)
print("c. Macierz z przekątną 0:\n", arr)
#d
greaterThan20 = arr[arr > 20]
print("d. > 20:\n", greaterThan20)


a. 6x6:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
b. Podmacierz 3x3 z lewego górnego rogu:
 [[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]
c. Macierz z przekątną 0:
 [[ 0  2  3  4  5  6]
 [ 7  0  9 10 11 12]
 [13 14  0 16 17 18]
 [19 20 21  0 23 24]
 [25 26 27 28  0 30]
 [31 32 33 34 35  0]]
d. > 20:
 [21 23 24 25 26 27 28 30 31 32 33 34 35]


a. Załaduj plik CSV z dowolnymi danymi – jako tablica Numpy (dane tylko liczbowe).

b. Oblicz średnią, medianę i odchylenie standardowe dla wybranej kolumny.


In [163]:
#a
import numpy as np

arr = np.genfromtxt("data/data.csv", delimiter=";", filling_values=np.nan,skip_header=1)
print("Data:\n", arr)

#b
column_index = 0
mean = np.nanmean(arr[:, column_index])
median = np.nanmedian(arr[:, column_index])
std_dev = np.nanstd(arr[:, column_index])
print("Mean:", mean)
print("Median:", median)
print("Std:", std_dev)



Data:
 [[ 1.  2.  3.]
 [ 2.  4.  6.]
 [ 3.  6.  9.]
 [ 4.  8. 12.]
 [ 5. 10. 15.]
 [ 6. 12. 18.]
 [ 7. 14. 21.]
 [ 8. 16. 24.]
 [ 9. 18. 27.]
 [10. 20. 30.]]
Mean: 5.5
Median: 5.5
Std: 2.8722813232690143


a. Utwórz tablicę z liczbami od -10 do 10.

b. Wyznacz tablicę prawd (True/False), które wskazują, które liczby są dodatnie.

c. Używając indeksowania logicznego, utwórz nową tablicę składającą się tylko z liczb
dodatnich.

In [164]:
#a
arr = np.arange(-10,11)
print("Array -10 to 10:\n", arr)
#b
trueOrFalse = arr > 0
print("True/False:\n", trueOrFalse)
#c
onlyTrueArr = arr[trueOrFalse]
print("Array only true:\n", onlyTrueArr)

Array -10 to 10:
 [-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9  10]
True/False:
 [False False False False False False False False False False False  True
  True  True  True  True  True  True  True  True  True]
Array only true:
 [ 1  2  3  4  5  6  7  8  9 10]


### Ćwiczenie 1

a. Przekonwertuj tablicę 1D na 2D

b. Utwórz następującą tablicę bez skomplikowanego kodowania. Używaj tylko funkcji numpy i poniższej tablicy wejściowej a.
    wejście: `a = np.array([1,2,3])`
    wyjście: `> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])`

c. wyświetl wspólne elementy dwóch tablic - korzystając tylko z funkcji numpy

d. usuń z jednej tablicy elementy, które występują w drugiej

e. zamień wiersze 1 i 2 w tablicy `arr = np.arange(9).reshape(3,3)`

f. utwórz tablicę 2D zawierającą liczby typu float od 5 do 10

g. Wyświetl tylko 3 miejsca po przecinku dla tablicy numpy

h. Wstaw wartości np.nan w 20 losowych pozycjach w zestawie danych iris_2d
    
    `# Input
     url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
     iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')`

In [165]:
import numpy as np
# a.
a = np.array([1, 2, 3, 4, 5])
a_2d = a.reshape((1, -1))
print("a. 1D to 2D:\n", a_2d)
# b.
a = np.array([1, 2, 3])
b = np.concatenate([np.repeat(a, 3), np.tile(a, 3)])
print("b. Custom array:\n", b)
# c.
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([4, 5, 6, 7, 8])
common_elements = np.intersect1d(arr1, arr2)
print("c. Common elements:\n", common_elements)
# d.
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([4, 5])
filtered_arr = np.setdiff1d(arr1, arr2)
print("d. Filtered array:\n", filtered_arr)
# e.
arr = np.arange(9).reshape(3, 3)
arr[[1, 2]] = arr[[2, 1]]
print("e. Swapped rows:\n", arr)
# f.
float_array = np.linspace(5, 10, num=10)
print("f. Float array from 5 to 10:\n", float_array)
# g.
arr = np.array([1.123456, 2.654321, 3.987654])
np.set_printoptions(precision=3)
print("g. Array with 3 decimal places:\n", arr)
# h.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
num_missing = 20
indices = np.random.choice(iris_2d.size, num_missing, replace=False)
iris_2d_flat = iris_2d.flatten()
iris_2d_flat[indices] = np.nan
iris_2d_with_nans = iris_2d_flat.reshape(iris_2d.shape)
print("h. Iris dataset with NaNs:\n", iris_2d_with_nans)


a. 1D to 2D:
 [[1 2 3 4 5]]
b. Custom array:
 [1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
c. Common elements:
 [4 5]
d. Filtered array:
 [1 2 3]
e. Swapped rows:
 [[0 1 2]
 [6 7 8]
 [3 4 5]]
f. Float array from 5 to 10:
 [ 5.          5.55555556  6.11111111  6.66666667  7.22222222  7.77777778
  8.33333333  8.88888889  9.44444444 10.        ]
g. Array with 3 decimal places:
 [1.123 2.654 3.988]
h. Iris dataset with NaNs:
 [[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [nan b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'5.4' b'3.7' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' nan b'Iri

### Ćwiczenie 2

Rozważmy wyrażenie wielomianowe


<a id='equation-np-polynom'></a>
$$
p(x) = a_0 + a_1 x + a_2 x^2 + \cdots a_N x^N = \sum_{n=0}^N a_n x^n \tag{1}
$$

Napisz funkcję wykorzystującą NumPy i tablice do obliczenia podanego wyrażenia

- Podpowiedź: Użyj `np.cumprod()`  



<a id='np-ex2'></a>

In [166]:
import numpy as np

def foo(a, x):
    x_array = np.full(len(a) - 1, x) #tworzy tablicę wypełnioną wartością x, o długości równej len(a) - 1 [3,3,3] dla x=3 i a o długości 4
    powers = np.concatenate(([1], np.cumprod(x_array))) #tworzy tablicę potęg x: [1, x, x^2, x^3]
    return np.sum(a * powers) # mnoży współczynniki a przez odpowiednie potęgi x i sumuje wyniki

a = np.array([5, 7, 9, 8]) # 5 + 7x + 9x^2+ 8x^3
x = 3
print(foo(a, x))

323


### Ćwiczenie 3

Niech `q` będzie tablicą NumPy o długości `n` z `q.sum() == 1`.

Załóżmy, że q reprezentuje [funkcję masy prawdopodobieństwa.](https://pl.wikipedia.org/wiki/Funkcja_masy_prawdopodobieństwa).

Chcemy wygenerować dyskretną zmienną losową $ x $
   tak, że $ \mathbb P\{x = i\} = q_i $.

Innymi słowy, `x` przyjmuje wartości z zakresu `range(len(q))` i `x = i` z prawdopodobieństwem `q[i]`.

Algorytm standardowy (transformacja odwrotna) jest następujący:

- Divide the unit interval $ [0, 1] $ into $ n $ subintervals $ I_0, I_1, \ldots, I_{n-1} $ such that the length of $ I_i $ is $ q_i $.  
- Draw a uniform random variable $ U $ on $ [0, 1] $ and return the $ i $ such that $ U \in I_i $.  


Prawdopodobieństwo wylosowania $ i $  to długość  $ I_i $, co jest równe $ q_i $.

Algorytm możemy zaimplementować w następujący sposób:

Jeśli nie widzisz, jak to działa, spróbuj przemyśleć przebieg działania na prostym przykładzie, na przykład `q = [0.25, 0.75]`. Pomocny jest rysunek na papierze.

Twoje zadanie polega na przyspieszeniu tego za pomocą NumPy, unikając jawnych pętli

- Podpowiedź: Skorzystaj z `np.searchsorted` i `np.cumsum`  


If you can, zaimplementuj tę funkcjonalność jako klasę o nazwie `DiscreteRV`,gdzie

- danymi dla instancji klasy jest wektor prawdopodobieństw `q`  
- klasa posiada metodę `draw()`, która zwraca jeden losowanie zgodnie z algorytmem opisanym powyżej


Jeśli jesteś w stanie, napisz metodę tak, aby `draw(k)` zwracało `k` losowań z  `q`.


<a id='np-ex3'></a>

In [167]:
from random import uniform
import time

def sample(q):
    a = 0.0
    U = uniform(0, 1)
    for i in range(len(q)):
        if a < U <= a + q[i]:
            return i
        a = a + q[i]

class DiscreteRV:
    def __init__(self, q):

        q = np.asarray(q, dtype=float)
        if not np.isclose(q.sum(), 1.0):
            raise ValueError("Prawdopodobieństwa muszą sumować się do 1.")
        self.q = q
        # Obliczamy dystrybuantę
        self.cdf = np.cumsum(q)

    def draw(self, k=None):

        if k is None:
            U = np.random.rand()  # losowa liczba z (0,1)
            return np.searchsorted(self.cdf, U)
        else:
            U = np.random.rand(k)  # k liczb z (0,1)
            return np.searchsorted(self.cdf, U)

q = np.array([0.1, 0.2, 0.3, 0.4])
X = DiscreteRV(q)

# Test sample
start = time.time()
for _ in range(10000000):
    sample(q)
print("Loop version:", time.time() - start)

# Test NumPy
start = time.time()
X.draw(10000000)
print("NumPy version:", time.time() - start)

Loop version: 9.050013303756714
NumPy version: 0.17603087425231934
